### GET CATEGORY
GET http://localhost:8000/api/category

### CREATE CATEGORY
POST http://localhost:8000/api/category/create
Content-Type: application/json

{
    "category": "Cafeteria"
}

### UPDATE CATEGORY
PUT http://localhost:8000/api/category/update/612482b815423a6dec52c925
Content-Type: application/json

{
    "category": "Fondos"
}

### DELETE CATEGORY
DELETE http://localhost:8000/api/category/delete/612482f4de619761002e673e