### GET CATEGORY
GET http://localhost:8000/cat/category

### CREATE CATEGORY
POST http://localhost:8000/cat/category/create
Content-Type: application/json

{
    "category": "Postre",
    "email": "stefano@gmail.com"
}

### UPDATE CATEGORY
PUT http://localhost:8000/cat/category/update/612406f0d518518f90836f8b
Content-Type: application/json

{
    "category": "Ensalada",
     "email": "admin@gmail.com"
}

### DELETE CATEGORY
DELETE http://localhost:8000/cat/category/delete/6124358f9057b77d6c6201da
Content-Type: application/json

{
     "email": "admin@gmail.com"
}