###GET ALL MENUS
GET http://localhost:8000/api/menu

###GET A SINGE MENU
GET http://localhost:8000/api/menu/61250d37fd69b7071c5ca7d0

###CREATE A NEW MENU
POST http://localhost:8000/api/menu/new
Content-Type: application/json

{
    "name" : "Ensalada César",
    "description" : "Lechuga romana, queso, pechuga de pollo y tomates",
    "category" : "Ensalada", 
    "price" : 5.99,
    //image tiene un object que es el objeto public_id y url cuando añadimos una imagen a cloudinary
    "image" : {
        "public_id": "test/w61qmyptvsleuhqpre3y",
        "url": "https://res.cloudinary.com/dsuchg5dl/image/upload/v1629863426/test/w61qmyptvsleuhqpre3y.jpg"
    }
}

###UPDATE A MENU
PUT http://localhost:8000/api/menu/update/61250d37fd69b7071c5ca7d0
Content-Type: application/json

{
   "name": "Arroz con Leche",
    "description": "Arroz dulce con leche condensado",
    "category": "Postre",
    "price": 3.99,
    "image": {
        "public_id": "test/jdtjcbc3wvwggaqvxmfs",
        "url": "https://res.cloudinary.com/dsuchg5dl/image/upload/v1629856256/test/jdtjcbc3wvwggaqvxmfs.jpg"
    }
}

###DELETE A MENU
DELETE http://localhost:8000/api/menu/delete/61250f81fd69b7071c5ca7d7