###GET ALL USERS
GET http://localhost:8000/api/users

###GET A SINGE USER
GET http://localhost:8000/api/user/612336b95faec366d4402cc7

###CREATE A NEW USER
POST http://localhost:8000/api/user/new
Content-Type: application/json

{
    "firstName" : "admin",
    "lastName" : "admin",
    "email" : "admin@gmail.com", 
    "password" : "12345",
    "confirmPassword" : "12345",
    "rol": 1
}

###UPDATE AN USER
PUT http://localhost:8000/api/user/update/6121a912514daa5fcc9ec18a
Content-Type: application/json

{
    "firstName" : "Alberto",
    "lastName" : "Queiroz",
    "email" : "alberto@gmail.com", 
    "password" : "1234",
    "confirmPassword" : "1234"
}

###DELETE AN USER
DELETE http://localhost:8000/api/user/delete/612335bc5faec366d4402cbe

###LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email" : "stefano@gmail.com",
    "password": "stefano"
}
###LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password": "12345"
}
###lOGOUT
GET http://localhost:8000/api/logout
